### ISSUE TITLE
build: update crate repository to https://github.com/RGB-WG/rgb-std

### ISSUE THREAD

**Issue by shuimuliang** [RGB-WG/rgb-std#129]
```toml
[workspace.package]
repository = "https://github.com/RGB-WG/rgb-std"
```
