### ISSUE TITLE
CFA transfer (with a NIA blank) fails

### ISSUE THREAD

**Issue by nicbus** [RGB-WG/rgb-std#149]
Using this [branch](https://github.com/nicbus/rgb-sandbox/tree/cfa) of rgb-sandbox, which includes support for CFA assets, I fail to transfer a CFA asset. The UTXO used as input for the transfer also has another (NIA) asset allocated, so a blank transition is also created. I get this error:
```
Validation failures:
- operation 1cc8530db258f5be43bbbb2afbf6787874c286267154d26d1c6b0d0a2e30a591 is invalid: unspecified error
```

Said branch of rgb-sandbox uses rgb-std from branch `v0.11` with the added fix for the blank contract ID (originally https://github.com/RGB-WG/rgb-std/pull/140).

Experimenting with the sandbox and rgb-lib, I found out that transfers succeed if I disable the `BlindingFactor` update that happens in `rgb-std`'s `compose_deterministic()`.
This can be tested using this [branch](https://github.com/nicbus/rgb-sandbox/tree/cfa_no_blank_blinding_update) of rgb-sandbox.

**Comment by dr-orlovsky** [comment]
Ok, this error happens since the resulting Pedersen blinding factors do not sum up for a blank transition. The simple solution is just to remove those three lines and not modify blinding factors for blank transitions. I think this makes a lot of sense. However, the question is why they do not sum up? The `complete_transition()` method modifies them in a way that they must be summing up! Thus, there is some hidden bug somewhere, and I want a full investigation not to miss something else important here...

One thing which I am worried about is why it was working before your PR? The change you introduced should change nothing in this regard.

Can you please test against https://github.com/RGB-WG/rgb-std/pull/150?

**Comment by dr-orlovsky** [comment]
Ok, this explains the question: before it was not working, but due to a different error happening before this one.

Investigating what doesn't work...

**Comment by dr-orlovsky** [comment]
Can you please help me locating `v0.11-fixed_blank_150` branch? Is it a sandbox branch or you meant something else?

**Comment by nicbus** [comment]
I realize I haven't been clear enough when specifying branches. The updated branch `v0.11-fixed_blank_150` I am referring to is for `rgb` on my [fork](https://github.com/nicbus/rgb/tree/v0.11-fixed_blank_150).

To make it simpler, I pushed this rgb-sandbox [branch](https://github.com/nicbus/rgb-sandbox/tree/cfa_150) that uses it.

**Comment by dr-orlovsky** [comment]
You just have to tell me that the `rgb` master doesn't compile. I have fixed it - you can now use in `sandbox` the master. The only thing you need is:

```toml
[patch.crates-io]
bp-util = { git = "https://github.com/BP-WG/bp-wallet", branch = "master" }
bp-wallet = { git = "https://github.com/BP-WG/bp-wallet", branch = "master" }
rgb-core = { git = "https://github.com/RGB-WG/rgb-core", branch = "master" }
rgb-std = { git = "https://github.com/RGB-WG/rgb-std", branch = "master" }
rgb-runtime = { git = "https://github.com/RGB-WG/rgb", branch = "master" }
rgb-wallet = { git = "https://github.com/RGB-WG/rgb", branch = "master" }
```
