### ISSUE TITLE
 variant or associated item not found in `Network`

### ISSUE THREAD

**Issue by hankouyu** [RGB-WG/rgb-std#257]
➜  rgb20-token git:(master) ✗ cargo build
   Compiling rgb-invoice v0.11.0-beta.6 (https://github.com/RGB-WG/rgb-std?branch=master#91bf0277)
error[E0599]: no variant or associated item named `Testnet4` found for enum `Network` in the current scope
   --> /Users/leslie/.cargo/git/checkouts/rgb-std-adbac1111552c725/91bf027/invoice/src/invoice.rs:158:22
    |
158 |             Network::Testnet4 => Self::BitcoinTestnet(data),
    |                      ^^^^^^^^
    |                      |
    |                      variant or associated item not found in `Network`
    |                      help: there is a variant with a similar name: `Testnet3`

For more information about this error, try `rustc --explain E0599`.
error: could not compile `rgb-invoice` (lib) due to 1 previous error

```toml
[package]
name = "rgb20-token"
version = "0.1.0"
edition = "2021"
resolver = "2"

[dependencies]
amplify = "4.6.0"
ascii-armor = "0.2.0"
strict_encoding = "2.7.0-beta.1"
strict_types = "2.7.0-beta.1"
aluvm = { version = "0.11.0-beta.4", features = ["log"] }
bp-core = "0.11.0-beta.4"
rgb-std = { version = "0.11.0-beta.4", features = ["serde", "fs"] }
serde = "1.0"
serde_json = "1.0"
sha2 = "0.10.8"
rgb-schemata = "0.11.0-beta.4"
hex = "0.4.3"

[dev-dependencies]
chrono = "0.4.31"
serde_yaml = "0.9.27"

[features]
all = []

[patch.crates-io]
commit_verify = { git = "https://github.com/LNP-BP/client_side_validation", branch = "master" }
bp-consensus = { git = "https://github.com/BP-WG/bp-core", branch = "master" }
bp-dbc = { git = "https://github.com/BP-WG/bp-core", branch = "master" }
bp-seals = { git = "https://github.com/BP-WG/bp-core", branch = "master" }
bp-core = { git = "https://github.com/BP-WG/bp-core", branch = "master" }
rgb-core = { git = "https://github.com/RGB-WG/rgb-core", branch = "master" }
rgb-std = { git = "https://github.com/RGB-WG/rgb-std", branch = "master" }
rgb-schemata = { git = "https://github.com/RGB-WG/rgb-schemata", branch = "master" }
```
